### ISSUE TITLE
FindBoost broken in boost 1.70.0

### ISSUE THREAD

**Issue by christopherwharrop-noaa** [ecmwf/ecbuild#11]
Perhaps you are already aware of this, but ecbuild fails to find boost and the unit_test_framework libraries for boost version 1.70.0.  This is not really a problem with ecbuild; it's a cmake/boost issue.  But I thought you might like to know that ecbuild users can work around this problem by adding the following setting to `ecbuild_setup_test_framework.cmake` right before the find_package call that looks for boost:

   `set( Boost_NO_BOOST_CMAKE ON )`

I found this workaround and some explanation for it [here](https://gitlab.kitware.com/cmake/cmake/issues/18865).

**Comment by tlmquintino** [comment]
@christopherwharrop-noaa the upcoming release of ecbuild 3 will remove any boost related test framework. Packages that use ecbuild will have to use the CMake macros directly.
In our stack we have removed Boost altogether, even the unit test framework, so we don't plan to continue to support it.
