### ISSUE TITLE
ecbuild cannot find netcdf.h

### ISSUE THREAD

**Issue by rkouznetsov** [ecmwf/ecbuild#17]
I try to compile development version of eccodes (2.18.0). It fails on missing netcdf.h unless I set
`export INCLUDE=$NETCDF_DIR/include:$INCLUDE`
before calling cmake.

I guess this has to be handled by ecbuild.
Thank you!

**Comment by wdeconinck** [comment]
Indeed, given that `netcdf.h` is located within `$NETCDF_DIR/include`, a `find_package(NetCDF)`  should work, which is confirmed by https://github.com/ecmwf/ecbuild/blob/master/cmake/FindNetCDF.cmake#L32-L41
