### ISSUE TITLE
Release with debug flags

### ISSUE THREAD

**Issue by danholdaway** [ecmwf/ecbuild#28]
We have been setting up some of our JCSDA continuous integration using the RelWithDebInfo build option. But we've noticed that this uses -O2 by default, making some of the testing quite slow. Is that intentional? We discussed at the JCSDA today and agreed that we would have expected to see the same optimization level as release.

**Comment by tlmquintino** [comment]
RelWithDebInfo is a build type from CMake. 
-O2 is a cmake default for RelWithDebInfo

Moreover setting -O3 is not guaranteed in most compilers to produce faster code, so it's a safer choice, especially when debug info is added in the bin code generation. 

We have added in ecbuild build type Production. It is similar to RelWithDebInfo but retains code Assertions. We use this for very sensitive production code where correctness and resilience (and a healthy level of paranoia) is higher priority than sheer performance. 

If you want to have -O3 with debug info I suggest you define your own build type in your project. This is quite simple and encouraged. 
Alternatively you can select build type None and then choose the combination of flags as you please.

**Comment by danholdaway** [comment]
OK, thanks @tlmquintino.
