### ISSUE TITLE
shallow cloning with ecbuild_bundle?

### ISSUE THREAD

**Issue by BenjaminTJohnson** [ecmwf/ecbuild#31]
In our project we use ecbuild_bundle to pull in several different repositories:

```
ecbuild_bundle( PROJECT foo GIT "https://github.com/foo" BRANCH feature/newthing  )
ecbuild_bundle( PROJECT bar GIT "https://github.com/bar"  BRANCH develop )
```

I'd like to shallow clone one or more of these repositories.   I understand the `GIT SHALLOW =1`  setting should enable shallow clones, but I'm not familiar enough with ecbuild options to know where to put this.

**Comment by oiffrig** [comment]
At the moment, ecbuild_bundle does not support shallow clones (pull requests welcome if you think this can be useful). GIT_SHALLOW is an option used by CMake's ExternalProject and FetchContent modules, it will have no effect on ecbuild_bundle behaviour.
