### ISSUE TITLE
Error using CTest

### ISSUE THREAD

**Issue by ComputerU** [ecmwf/ecbuild#35]
Hi,

I'm trying to install ecbuild. I followed the instructions on the installation page. However, when I get to ctest 2 of the 20 tests fail. I've tried installing different versions of cmake (3.16.3-ubuntu and 3.20.1) and I've tried also setting the folders differently. I'm not really sure why it is failing though. I've checked the last test log. It fails tests 6 and 13:
6 - ECBUILD-415 (Failed)
13 - test_ecbuild_regex_escape (Failed)

All of the blanked out spots are $HOME

![image](https://user-images.githubusercontent.com/80340633/110951480-04b2c300-833d-11eb-8d64-5922a4856c9f.png)

![image](https://user-images.githubusercontent.com/80340633/110951773-578c7a80-833d-11eb-888b-4c395bee4451.png)

**Comment by oiffrig** [comment]
Hi @ComputerU, thanks for your report. I will have a look.

You can safely ignore the failing tests in the meantime.

**Comment by oiffrig** [comment]
Fixed in branch `develop`.
