### ISSUE TITLE
Building both shared and static library

### ISSUE THREAD

**Issue by StegmannJCSDA** [ecmwf/ecbuild#38]
Is there a recommended way of building both a shared *and* static version of a library with ecbuild in one pass?
Would the following naive approach work?
```cmake
ecbuild_add_library(TARGET ${PROJECT_NAME} TYPE SHARED SOURCES ${${PROJECT_NAME}_src_files})
ecbuild_add_library(TARGET ${PROJECT_NAME}_static TYPE STATIC SOURCES ${${PROJECT_NAME}_src_files})
```

**Comment by oiffrig** [comment]
You can set the `BUILD_SHARED_LIBS` CMake variable to `BOTH`, which will have ecbuild make both a shared and a static version of every library (the target for the static library will have a `-static` suffix but the output name will not).

A caveat though: if you use the `{PRIVATE,PUBLIC}_LIBS` arguments, ecbuild will not look for a `-static` alternative of these targets when making the static version. You can use `target_link_libraries` directly to handle this case.

Alternatively, the solution you suggested works and has the advantage of being explicit. You may want to add `OUTPUT_NAME ${PROJECT_NAME}` to the static library if you do not want the actual files to be named differently (`libfoo.so` and `libfoo.a` instead of `libfoo.so` and `libfoo_static.a`, if your project name is `foo`).

**Comment by StegmannJCSDA** [comment]
Thank you. So far I tried the approaches but ran into problems with both of them. We're linking against Fortran netCDF and in either case the module can't be opened:
```shell

   74 |   USE netcdf
      |       1
Fatal Error: Cannot open module file 'netcdf.mod' for reading at (1): No such file or directory
compilation terminated.
```
Perhaps this is related:

> A caveat though: if you use the {PRIVATE,PUBLIC}_LIBS arguments, ecbuild will not look for a -static alternative of these targets when making the static version. You can use target_link_libraries directly to handle this case.

**Comment by wdeconinck** [comment]
You should also be able to use BOTH as the TYPE for your target.
Did you link to NetCDF as follows?
```
find_package( NetCDF REQUIRED COMPONENTS Fortran )
ecbuild_add_library( TARGET <library-name> 
                     TYPE BOTH
                     SOURCES <library-sources>
                     PUBLIC_LIBS NetCDF::NetCDF_Fortran )
```
Do you only encounter the problem only with the static library or as well with the shared?

**Comment by StegmannJCSDA** [comment]
For netCDF we have the following:
```cmake
find_package( NetCDF REQUIRED COMPONENTS Fortran )
...
target_link_libraries(${PROJECT_NAME} PUBLIC NetCDF::NetCDF_Fortran)
```
I tried:
```cmake
ecbuild_add_library(TARGET ${PROJECT_NAME} TYPE BOTH SOURCES ${${PROJECT_NAME}_src_files})
```
-and got the same result.

When I just use:
```cmake
ecbuild_add_library(TARGET ${PROJECT_NAME} TYPE STATIC SOURCES ${${PROJECT_NAME}_src_files})
```
I don't run into any problems, but in that case I can only build either the static *or* shared library at any given time.

**Comment by wdeconinck** [comment]
When you don't use the "PUBLIC_LIBS" keyword within `ecbuild_add_library` then you have to provide the `target_link_libraries` command for both targets as:
```cmake
target_link_libraries(${PROJECT_NAME}        PUBLIC NetCDF::NetCDF_Fortran)
target_link_libraries(${PROJECT_NAME}-static PUBLIC NetCDF::NetCDF_Fortran)
```
They really are two distinct targets.

**Comment by StegmannJCSDA** [comment]
Yes, that was what I used when I specified two targets:
```cmake
ecbuild_add_library(TARGET ${PROJECT_NAME} TYPE SHARED SOURCES ${${PROJECT_NAME}_src_files})
ecbuild_add_library(TARGET ${PROJECT_NAME}_static TYPE STATIC SOURCES ${${PROJECT_NAME}_src_files})
```
The netCDF problem occurs when I use:
```cmake 
ecbuild_add_library(TARGET ${PROJECT_NAME} TYPE BOTH SOURCES ${${PROJECT_NAME}_src_files})
```

**Comment by wdeconinck** [comment]
I have tried to reproduce but see no problem with:

### CMakeLists.txt
```cmake
cmake_minimum_required( VERSION 3.12 FATAL_ERROR )

find_package( ecbuild 3.6 REQUIRED )

project( myproject VERSION 0.0.0 LANGUAGES Fortran )

find_package( NetCDF REQUIRED COMPONENTS Fortran )

ecbuild_add_library( TARGET  ${PROJECT_NAME}
                     TYPE    BOTH
                     SOURCES myproject.F90
                     PUBLIC_LIBS NetCDF::NetCDF_Fortran )

# Alternative way without PUBLIC_LIBS argument
ecbuild_add_library( TARGET  ${PROJECT_NAME}_alternative
                     TYPE    BOTH
                     SOURCES myproject.F90 )
target_link_libraries( ${PROJECT_NAME}_alternative         PUBLIC NetCDF::NetCDF_Fortran )
target_link_libraries( ${PROJECT_NAME}_alternative-static  PUBLIC NetCDF::NetCDF_Fortran )
```
### myproject.F90
```Fortran
module myproject
implicit none
contains
subroutine mysubroutine
use netcdf
end subroutine
end module
```

**Comment by StegmannJCSDA** [comment]
As an update:

It looks like this solution actually works and it produces both static and shared library at the same time with gfortran:
```cmake
ecbuild_add_library(TARGET ${PROJECT_NAME} TYPE SHARED SOURCES ${${PROJECT_NAME}_src_files})
ecbuild_add_library(TARGET ${PROJECT_NAME}_static TYPE STATIC SOURCES ${${PROJECT_NAME}_src_files})
```
The only problem is that Intel Fortran is throwing and unspecified error during compilation for this solution, probably running out of memory.

**Comment by StegmannJCSDA** [comment]
Hello Willem @wdeconinck, thank you for testing the configuration. I was also able to successfully build your test example with gfortran and the desired outcome.
The netCDF issue still persists with the CRTM, but specifying both `SHARED` and `STATIC` provides an acceptable solution for now. I'll still have a closer look at the netCDF problem later but otherwise this issue can be closed.

**Comment by wdeconinck** [comment]
Thank you for verification!
