### ISSUE TITLE
Defunct link on main website

### ISSUE THREAD

**Issue by cponder** [ecmwf/ecbuild#39]
This page here
> https://github.com/ecmwf/ecbuild

has this link on the upper righthand side
> [software.ecmwf.int/wiki/display/ecbuild](https://software.ecmwf.int/wiki/display/ecbuild)

If I actually click on the link, though, it gets me to a page that says this:
```
Please update your bookmarks
The domain provided `software.ecmwf.int` should now be `confluence.ecmwf.int` and the uri prefix `/wiki` has been removed.
Please use the following:
https://confluence.ecmwf.int/display/ecbuild
```

**Comment by cponder** [comment]
I tried to click on the new link but it just got me to some kind of login page, I don't know if that's what you want it to do.

**Comment by oiffrig** [comment]
Thanks for pointing this out. I replaced the link with something more useful.
