### ISSUE TITLE
What are the features of the ecbuild and why should one use it?

### ISSUE THREAD

**Issue by adamryczkowski** [ecmwf/ecbuild#5]
My friend recommended that I take a look on `ecbuild`. Unfortunately, the project's wiki is unavailable without login. That's why I turn to you here in hope you could help me and answer some of the questions:

1. What problems does the project try to solve? 
2. What is the list of its features?
3. Does it support superbuild? Does it support building external dependencies?
4. Does it support building cherry-picked targets?
5. Does it support building targets from any directory (not the one in which targets are defined)?
6. Does it support automatic naming of targets (so one can build several versions of the same executable in one build)?

**Comment by wdeconinck** [comment]
ecbuild is in fact a set of CMake functions and macros that give our projects a unified way of interoperating, and addresses some intricacies of running on various architectures used at ECMWF.  So if CMake addresses your questions, so does ecbuild :)
We are aware of the pages being not publicly accessible and will address this in the near future.

**Comment by aerorahul** [comment]
FWIW, the in-source documentation of ecBuild can be built with `Sphinx`

```
git clone https://github.com/jcsda/ecbuild
mkdir build
cd build
cmake ../ecbuild
make html_docs
```

Open `doc/html/index.html` in your favourite browser.
