### ISSUE TITLE
Flang `-fsanitize=<check>` flag not recognized

### ISSUE THREAD

**Issue by awnawab** [ecmwf/ecbuild#51]
When compiling Fortran using the (new, not legacy) flang compiler, passing the debugging flag `-fsanitize=<check>` to `ecbuild_add_fortran_flags()` results in a 'CRITICAL - Fortran compiler does not recognize flag error'. However the flag definitely does exist, and can be added using the default CMake `add_compile/link_options()`.

**Comment by wdeconinck** [comment]
`ecbuild_add_fortran_flags()` compiles a dummy program with that flag to check.
Something must go wrong during compilation to result in failure.
Output can be inspected in the build dir, in files: CMakeFiles/CMakeError.log and CMakeFiles/CMakeOutput.log.

**Comment by awnawab** [comment]
Then I think I know what's going on. This compiler flag also needs to be added as a linker flag. Is there an option in `ecbuild_add_fortran_flags()` to also add the flag to the linking step?

**Comment by wdeconinck** [comment]
In the past I have just added on command line:
```
-DCMAKE_C_FLAGS='-fsanitize=address -fno-omit-frame-pointer' \
-DCMAKE_EXE_LINKER_FLAGS=-fsanitize=address
```
This was with clang/clang++. I had to disable anything related to Fortran as I was using gfortran at the time and the link flag did not work.
